---
title: Verf een achtergrond in één kleur
hero_image: images/banner.png
description: Verf een achtergrond in één kleur
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Verf een achtergrond in één kleur
