title: scratch-paint-single-colour-backdrop
hero_image: images/banner.png
description: scratch-paint-single-colour-backdrop description
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
