---
title: Pinte um cenário de cor única
hero_image: images/banner.png
description: Pinte um cenário de cor única
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Pinte um cenário de cor única
