---
title: Paint a single colour backdrop
hero_image: images/banner.png
description: Paint a single colour backdrop
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Paint a single colour backdrop
