---
title: Pinta un fondo de un solo color
hero_image: images/banner.png
description: Pinta un fondo de un solo color
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Pinta un fondo de un solo color
