---
title: Pomaluj tło w jednym kolorze
hero_image: images/banner.png
description: Pomaluj tło w jednym kolorze
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Pomaluj tło w jednym kolorze
