---
title: Peindre un arrière-plan d'une seule couleur
hero_image: images/banner.png
description: Peindre un arrière-plan d'une seule couleur
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - 
    title: Peindre un arrière-plan d'une seule couleur
