---
title: Disegna uno sfondo monocromatico
hero_image: images/banner.png
description: Disegna uno sfondo monocromatico
version: 4
listed: false
copyedit: false
last_tested: "2021-05-04"
steps:
  - title: Disegna uno sfondo monocromatico
